volumes:
  volume_xpra_2:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: volume_xpra_2
  xdg_runtime:
    driver: local
    driver_opts:
      type: tmpfs
      device: tmpfs
      o: size=64m,uid=1000  # Adjust size and uid as needed
services:
  xpra:
    build:
      context: .
      dockerfile: Dockerfile1 
    image: tswetnam/xpra:bionic
    container_name: xpra
    hostname: xpra
    restart: always
    ports:
      - '9876:9876'
    volumes:
      - volume_xpra_2:/usr/share/xpra
      - xdg_runtime:/tmp/xdg # Mount the tmpfs volume
    environment:
      - DISPLAY=:14  # Specify the display number here
      - XPRA_HTML=1
      - XPRA_X11=1
      - XPRA_XFCE=1  # Biến môi trường để sử dụng XFCE
      - XDG_RUNTIME_DIR=/tmp/xdg
    command: /bin/bash -c "mkdir -p /tmp/xdg/xpra && xpra start :14 --bind-tcp=0.0.0.0:9876 --html=on --start=startxfce4 && sleep infinity"