volumes:
  xpra_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: xpra_volume
services:
  xpra:
    image: hieuxpra
    container_name: hieuxfce2
    hostname: xpra
    restart: always
    expose:
      - '9876'
    volumes:
      - xpra_volume:/usr/share/xpra
    deploy:
      resources:
        limits:
          cpus: '1'
          memory: 1G
    mem_limit: 1g
    memswap_limit: 22g
  nginx123:
    image: nginx
    container_name: nginx123
    ports:
      - 81:80
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - xpra_volume:/usr/share/xpra
    depends_on:
      - xpra