volumes:
  xpra_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: xpra_volume
services:
  xpra:
    image: hieutestxfce2
    container_name: hieuxfce2
    hostname: xpra
    restart: always
    expose:
      - '9876'
    volumes:
      - xpra_volume:/usr/share/xpra
  nginx:
    image: nginx
    ports:
      - "81:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - xpra