volumes:
  xpra_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: xpra_volume
services:
  xpra:
    image: hieutestxfce2
    container_name: hieuxfce2
    hostname: xpra
    restart: always
    ports:
      - '9871:9876'
    volumes:
      - xpra_volume:/usr/share/xpra