volumes:
  xpra_volume:
    driver: local
    driver_opts:
      o: bind
      type: none
      device: xpra_volume
services:
  xpra:
    image: hieutestxfce2
    container_name: hieuxfce2
    hostname: xpra
    restart: always
    expose:
      - '9876'
    volumes:
      - xpra_volume:/usr/share/xpra
    deploy:
      resources:
        limits:
          cpus: '2'
          memory: 2G
    mem_limit: 2g
    memswap_limit: 22g
  nginx:
    image: nginx
    ports:
      - "81:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
    depends_on:
      - xpra
  auth_changer:
    image: alpine
    volumes:
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./change_auth.sh:/change_auth.sh
      - ./auth_credentials.txt:/auth_credentials.txt
      - ./init_auth_changer.sh:/init_auth_changer.sh
    command: sh /init_auth_changer.sh